# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79dc6ba1f272ed4428865d6394548c93c44a250335a455df0222d0f0af9d7db5705a9083796d86ae271242e7afc7b8137211ff8c3241dfb991ff1359f0abed9e

test:
  secret_key_base: 7f15bdc1248293a64c42538407ccb61cc613b20cc633912bc8c608135dd4ca633d373bc104c452eff66d5ce94c6363f4f19d00610ffade742d00545ba27af0b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
